networks:
  composition_network:
    external: true

services:
  composition-app:
    build:
      context: ./composition
      dockerfile: /Dockerfile
    networks:
      - composition_network
    deploy:
      replicas: 5

  score-app:
    container_name: score-app
    build:
      context: ./score
      dockerfile: /Dockerfile
    ports:
      - "50052:50051"
    networks:
      - composition_network

  auth-app:
    container_name: auth-app
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "50053:50051"
    networks:
      - composition_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - composition_network
