# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"6\n\x13\x41uthenticateRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\x14\x41uthenticateResponse\x12\x16\n\x0e\x61llowed_access\x18\x01 \x01(\x08\x32\x43\n\x04\x41uth\x12;\n\x0c\x41uthenticate\x12\x14.AuthenticateRequest\x1a\x15.AuthenticateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHENTICATEREQUEST']._serialized_start=14
  _globals['_AUTHENTICATEREQUEST']._serialized_end=68
  _globals['_AUTHENTICATERESPONSE']._serialized_start=70
  _globals['_AUTHENTICATERESPONSE']._serialized_end=116
  _globals['_AUTH']._serialized_start=118
  _globals['_AUTH']._serialized_end=185
# @@protoc_insertion_point(module_scope)
